name: "build-push"

on:
  push:
    branches:
    - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: make docker-login

    - name: Build
      env:
        GO_BUILD_PLATFORMS: linux-amd64
      run: make docker-build

    - name: Push
      run: make docker-push

