on: [push]
name: CI
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    runs-on: ubuntu-latest-4-cores

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.mod
        cache-dependency-path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.sum
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.11'
    - name: Execute Tests
      run: |
        go mod download
        go mod verify
        make test
      env:
        CI: true
