on: [push]
name: CI
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.19.x]

    runs-on: ubuntu-latest-4-cores

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.10.0'
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Execute Tests
      run: |
        go mod download
        go mod verify
        make test
      env:
        CI: true
