name: CI

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    runs-on: ubuntu-latest-4-cores

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.mod
        cache-dependency-path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.sum
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.11'
    - name: Execute Tests
      run: |
        go mod download
        go mod verify
        make test
      env:
        CI: true

  test-fips:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lynx
    - uses: chainguard-dev/setup-chainctl@main
      with:
        identity: ee399b4c72dd4e58e3d617f78fc47b74733c9557/f6f21541a4fdea18
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.mod
        cache-dependency-path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.sum
    - name: Execute Tests
      run: |
        go env
        go mod download
        go mod verify
        go test -mod=readonly -failfast -v ./service/...
      env:
        CI: true
        CGO_ENABLED: 1
        GOEXPERIMENT: boringcrypto
